### ISSUE TITLE
Getting ready for submission

### ISSUE THREAD

**Issue by rybarix** [SandroRybarik/SJ-2022-littleXML-parser#2]
# TODOs to finalize

## test.js
- [x] Add another 1 test case for each test category

## 1.md
- [x] Write down the test cases from test.js file in MD

## 4.md
- [x] Write down on paper FIRST / FOLLOW sets for grammar in `3.0.md`
- [x] Add photo into repo and add it to 4.md

## 5.md
- [x] Write down parsing table into excel and make screenshot of it
- [x] Add screenshot to 5.md

**Comment by KToldy** [comment]
Done
